#!/bin/bash

# Define command-line arguments

RESOURCE_TYPE=$1
if [ -z "$2" ]; then
NAME_SPACE=default
else 
NAME_SPACE=$2
fi

# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n $NAME_SPACE | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"т
  printf "%s\t%-20s\t%-40s\t%-20s\t%s\n" $RESOURCE_TYPE $NAME_SPACE $NAME $CPU $MEMORY
done
